"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.node_address_dto import NodeAddressDto


class TestNodeAddressDto(unittest.TestCase):
    """NodeAddressDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeAddressDto(self):
        """Test NodeAddressDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodeAddressDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
