"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.metric_dto import MetricDto
globals()['MetricDto'] = MetricDto
from qovery-ws.model.service_metrics_dto import ServiceMetricsDto


class TestServiceMetricsDto(unittest.TestCase):
    """ServiceMetricsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceMetricsDto(self):
        """Test ServiceMetricsDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceMetricsDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
