# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.unit_dto import UnitDto  # noqa: E501

class TestUnitDto(unittest.TestCase):
    """UnitDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitDto(self):
        """Test UnitDto"""
        # inst = UnitDto()

if __name__ == '__main__':
    unittest.main()
