# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.node_resource_dto import NodeResourceDto

class TestNodeResourceDto(unittest.TestCase):
    """NodeResourceDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeResourceDto:
        """Test NodeResourceDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeResourceDto`
        """
        model = NodeResourceDto()
        if include_optional:
            return NodeResourceDto(
                cpu_milli = 0,
                ephemeral_storage_gib = 0,
                memory_mib = 0,
                pods = 0
            )
        else:
            return NodeResourceDto(
                cpu_milli = 0,
                ephemeral_storage_gib = 0,
                memory_mib = 0,
                pods = 0,
        )
        """

    def testNodeResourceDto(self):
        """Test NodeResourceDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
