# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.service_list_pods_response_dto import ServiceListPodsResponseDto

class TestServiceListPodsResponseDto(unittest.TestCase):
    """ServiceListPodsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceListPodsResponseDto:
        """Test ServiceListPodsResponseDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceListPodsResponseDto`
        """
        model = ServiceListPodsResponseDto()
        if include_optional:
            return ServiceListPodsResponseDto(
                pods = [
                    qovery-ws.models.pod_dto.PodDto(
                        name = '', 
                        ports = [
                            0
                            ], )
                    ]
            )
        else:
            return ServiceListPodsResponseDto(
                pods = [
                    qovery-ws.models.pod_dto.PodDto(
                        name = '', 
                        ports = [
                            0
                            ], )
                    ],
        )
        """

    def testServiceListPodsResponseDto(self):
        """Test ServiceListPodsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
