# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qovery-ws.api.service_list_pods_api import ServiceListPodsApi  # noqa: E501


class TestServiceListPodsApi(unittest.TestCase):
    """ServiceListPodsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceListPodsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_handle_service_list_pods_request(self) -> None:
        """Test case for handle_service_list_pods_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
