"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.node_pod_info_dto import NodePodInfoDto


class TestNodePodInfoDto(unittest.TestCase):
    """NodePodInfoDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodePodInfoDto(self):
        """Test NodePodInfoDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodePodInfoDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
