"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qovery-ws
from qovery-ws.api.cluster_status_api import ClusterStatusApi  # noqa: E501


class TestClusterStatusApi(unittest.TestCase):
    """ClusterStatusApi unit test stubs"""

    def setUp(self):
        self.api = ClusterStatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_handle_cluster_status_request(self):
        """Test case for handle_cluster_status_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
