# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.service_infra_log_response_dto import ServiceInfraLogResponseDto  # noqa: E501

class TestServiceInfraLogResponseDto(unittest.TestCase):
    """ServiceInfraLogResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceInfraLogResponseDto:
        """Test ServiceInfraLogResponseDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceInfraLogResponseDto`
        """
        model = ServiceInfraLogResponseDto()  # noqa: E501
        if include_optional:
            return ServiceInfraLogResponseDto(
                created_at = 56,
                message = ''
            )
        else:
            return ServiceInfraLogResponseDto(
                created_at = 56,
                message = '',
        )
        """

    def testServiceInfraLogResponseDto(self):
        """Test ServiceInfraLogResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
