"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.node_address_dto import NodeAddressDto
from qovery-ws.model.node_condition_dto import NodeConditionDto
from qovery-ws.model.node_pod_info_dto import NodePodInfoDto
from qovery-ws.model.node_resource_dto import NodeResourceDto
from qovery-ws.model.node_taint_dto import NodeTaintDto
globals()['NodeAddressDto'] = NodeAddressDto
globals()['NodeConditionDto'] = NodeConditionDto
globals()['NodePodInfoDto'] = NodePodInfoDto
globals()['NodeResourceDto'] = NodeResourceDto
globals()['NodeTaintDto'] = NodeTaintDto
from qovery-ws.model.cluster_node_dto import ClusterNodeDto


class TestClusterNodeDto(unittest.TestCase):
    """ClusterNodeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterNodeDto(self):
        """Test ClusterNodeDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterNodeDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
