"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.container_state_dto import ContainerStateDto
from qovery-ws.model.int_none_type import IntNoneType
from qovery-ws.model.service_state_dto import ServiceStateDto
globals()['ContainerStateDto'] = ContainerStateDto
globals()['ServiceStateDto'] = ServiceStateDto
globals()['int, none_type'] = int, none_type
from qovery-ws.model.container_status_dto_current_state import ContainerStatusDtoCurrentState


class TestContainerStatusDtoCurrentState(unittest.TestCase):
    """ContainerStatusDtoCurrentState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerStatusDtoCurrentState(self):
        """Test ContainerStatusDtoCurrentState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContainerStatusDtoCurrentState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
