"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.unit_dto import UnitDto


class TestUnitDto(unittest.TestCase):
    """UnitDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitDto(self):
        """Test UnitDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnitDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
