# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.resource_status_dto import ResourceStatusDto  # noqa: E501

class TestResourceStatusDto(unittest.TestCase):
    """ResourceStatusDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceStatusDto(self):
        """Test ResourceStatusDto"""
        # inst = ResourceStatusDto()

if __name__ == '__main__':
    unittest.main()
