# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.service_metrics_dto import ServiceMetricsDto

class TestServiceMetricsDto(unittest.TestCase):
    """ServiceMetricsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceMetricsDto:
        """Test ServiceMetricsDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceMetricsDto`
        """
        model = ServiceMetricsDto()
        if include_optional:
            return ServiceMetricsDto(
                cpu = qovery-ws.models.metric_dto.MetricDto(
                    current = 0, 
                    current_percent = 0, 
                    limit = 0, 
                    name = '', 
                    status = 'OK', 
                    unit = 'mCPU', ),
                memory = qovery-ws.models.metric_dto.MetricDto(
                    current = 0, 
                    current_percent = 0, 
                    limit = 0, 
                    name = '', 
                    status = 'OK', 
                    unit = 'mCPU', ),
                pod_name = '',
                storages = [
                    qovery-ws.models.metric_dto.MetricDto(
                        current = 0, 
                        current_percent = 0, 
                        limit = 0, 
                        name = '', 
                        status = 'OK', 
                        unit = 'mCPU', )
                    ]
            )
        else:
            return ServiceMetricsDto(
                cpu = qovery-ws.models.metric_dto.MetricDto(
                    current = 0, 
                    current_percent = 0, 
                    limit = 0, 
                    name = '', 
                    status = 'OK', 
                    unit = 'mCPU', ),
                memory = qovery-ws.models.metric_dto.MetricDto(
                    current = 0, 
                    current_percent = 0, 
                    limit = 0, 
                    name = '', 
                    status = 'OK', 
                    unit = 'mCPU', ),
                pod_name = '',
                storages = [
                    qovery-ws.models.metric_dto.MetricDto(
                        current = 0, 
                        current_percent = 0, 
                        limit = 0, 
                        name = '', 
                        status = 'OK', 
                        unit = 'mCPU', )
                    ],
        )
        """

    def testServiceMetricsDto(self):
        """Test ServiceMetricsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
