# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qovery-ws.api.service_status_api import ServiceStatusApi


class TestServiceStatusApi(unittest.TestCase):
    """ServiceStatusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceStatusApi()

    def tearDown(self) -> None:
        pass

    def test_handle_service_status_request(self) -> None:
        """Test case for handle_service_status_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
