"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.service_type import ServiceType


class TestServiceType(unittest.TestCase):
    """ServiceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceType(self):
        """Test ServiceType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
