"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qovery-ws
from qovery-ws.api.service_list_pods_api import ServiceListPodsApi  # noqa: E501


class TestServiceListPodsApi(unittest.TestCase):
    """ServiceListPodsApi unit test stubs"""

    def setUp(self):
        self.api = ServiceListPodsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_handle_service_list_pods_request(self):
        """Test case for handle_service_list_pods_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
