"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.service_state_dto import ServiceStateDto


class TestServiceStateDto(unittest.TestCase):
    """ServiceStateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceStateDto(self):
        """Test ServiceStateDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceStateDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
