"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.service_log_response_dto import ServiceLogResponseDto


class TestServiceLogResponseDto(unittest.TestCase):
    """ServiceLogResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceLogResponseDto(self):
        """Test ServiceLogResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceLogResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
