"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.node_resource_dto import NodeResourceDto


class TestNodeResourceDto(unittest.TestCase):
    """NodeResourceDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeResourceDto(self):
        """Test NodeResourceDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodeResourceDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
