# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.service_type import ServiceType  # noqa: E501

class TestServiceType(unittest.TestCase):
    """ServiceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceType(self):
        """Test ServiceType"""
        # inst = ServiceType()

if __name__ == '__main__':
    unittest.main()
