# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qovery-ws.api.cluster_status_api import ClusterStatusApi


class TestClusterStatusApi(unittest.TestCase):
    """ClusterStatusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClusterStatusApi()

    def tearDown(self) -> None:
        pass

    def test_handle_cluster_status_request(self) -> None:
        """Test case for handle_cluster_status_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
