"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.container_state_terminated_dto import ContainerStateTerminatedDto


class TestContainerStateTerminatedDto(unittest.TestCase):
    """ContainerStateTerminatedDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerStateTerminatedDto(self):
        """Test ContainerStateTerminatedDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContainerStateTerminatedDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
