"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.pod_dto import PodDto
globals()['PodDto'] = PodDto
from qovery-ws.model.service_list_pods_response_dto import ServiceListPodsResponseDto


class TestServiceListPodsResponseDto(unittest.TestCase):
    """ServiceListPodsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceListPodsResponseDto(self):
        """Test ServiceListPodsResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceListPodsResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
