"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.resource_status_dto import ResourceStatusDto


class TestResourceStatusDto(unittest.TestCase):
    """ResourceStatusDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceStatusDto(self):
        """Test ResourceStatusDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResourceStatusDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
