"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.pod_dto import PodDto


class TestPodDto(unittest.TestCase):
    """PodDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPodDto(self):
        """Test PodDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PodDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
