# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.service_state_dto import ServiceStateDto

class TestServiceStateDto(unittest.TestCase):
    """ServiceStateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceStateDto(self):
        """Test ServiceStateDto"""
        # inst = ServiceStateDto()

if __name__ == '__main__':
    unittest.main()
