"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.int_none_type import IntNoneType
globals()['int, none_type'] = int, none_type
from qovery.model.service_infra_log_response_dto import ServiceInfraLogResponseDto


class TestServiceInfraLogResponseDto(unittest.TestCase):
    """ServiceInfraLogResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceInfraLogResponseDto(self):
        """Test ServiceInfraLogResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceInfraLogResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
