"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.environment_status_dto import EnvironmentStatusDto
globals()['EnvironmentStatusDto'] = EnvironmentStatusDto
from qovery.model.service_status_dto import ServiceStatusDto


class TestServiceStatusDto(unittest.TestCase):
    """ServiceStatusDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceStatusDto(self):
        """Test ServiceStatusDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceStatusDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
