"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qovery-ws
from qovery-ws.api.infra_status_api import InfraStatusApi  # noqa: E501


class TestInfraStatusApi(unittest.TestCase):
    """InfraStatusApi unit test stubs"""

    def setUp(self):
        self.api = InfraStatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_handle_infra_status_request(self):
        """Test case for handle_infra_status_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
