"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.container_state_terminated_dto import ContainerStateTerminatedDto
globals()['ContainerStateTerminatedDto'] = ContainerStateTerminatedDto
from qovery-ws.model.container_status_dto_last_terminated_state import ContainerStatusDtoLastTerminatedState


class TestContainerStatusDtoLastTerminatedState(unittest.TestCase):
    """ContainerStatusDtoLastTerminatedState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerStatusDtoLastTerminatedState(self):
        """Test ContainerStatusDtoLastTerminatedState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContainerStatusDtoLastTerminatedState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
