# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.metric_dto import MetricDto

class TestMetricDto(unittest.TestCase):
    """MetricDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetricDto:
        """Test MetricDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetricDto`
        """
        model = MetricDto()
        if include_optional:
            return MetricDto(
                current = 0,
                current_percent = 0,
                limit = 0,
                name = '',
                status = 'OK',
                unit = 'mCPU'
            )
        else:
            return MetricDto(
                current = 0,
                current_percent = 0,
                limit = 0,
                status = 'OK',
                unit = 'mCPU',
        )
        """

    def testMetricDto(self):
        """Test MetricDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
