"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qovery-ws
from qovery-ws.api.logs_api import LogsApi  # noqa: E501


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self):
        self.api = LogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_handle_infra_logs_request(self):
        """Test case for handle_infra_logs_request

        """
        pass

    def test_handle_service_logs_request(self):
        """Test case for handle_service_logs_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
