# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qovery-ws.api.service_metrics_api import ServiceMetricsApi  # noqa: E501


class TestServiceMetricsApi(unittest.TestCase):
    """ServiceMetricsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceMetricsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_handle_metrics_request(self) -> None:
        """Test case for handle_metrics_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
