# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.node_taint_dto import NodeTaintDto

class TestNodeTaintDto(unittest.TestCase):
    """NodeTaintDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeTaintDto:
        """Test NodeTaintDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeTaintDto`
        """
        model = NodeTaintDto()
        if include_optional:
            return NodeTaintDto(
                effect = '',
                key = '',
                value = ''
            )
        else:
            return NodeTaintDto(
                effect = '',
                key = '',
                value = '',
        )
        """

    def testNodeTaintDto(self):
        """Test NodeTaintDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
