"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.int_none_type import IntNoneType
from qovery-ws.model.service_state_dto import ServiceStateDto
globals()['ServiceStateDto'] = ServiceStateDto
globals()['int, none_type'] = int, none_type
from qovery-ws.model.container_state_dto import ContainerStateDto


class TestContainerStateDto(unittest.TestCase):
    """ContainerStateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerStateDto(self):
        """Test ContainerStateDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContainerStateDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
