# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.node_pod_info_dto import NodePodInfoDto

class TestNodePodInfoDto(unittest.TestCase):
    """NodePodInfoDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodePodInfoDto:
        """Test NodePodInfoDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodePodInfoDto`
        """
        model = NodePodInfoDto()
        if include_optional:
            return NodePodInfoDto(
                cpu_milli_limit = 0,
                cpu_milli_request = 0,
                environment_id = '',
                images_version = {
                    'key' : ''
                    },
                memory_mib_limit = 0,
                memory_mib_request = 0,
                name = '',
                namespace = '',
                project_id = '',
                service_id = ''
            )
        else:
            return NodePodInfoDto(
                images_version = {
                    'key' : ''
                    },
                name = '',
                namespace = '',
        )
        """

    def testNodePodInfoDto(self):
        """Test NodePodInfoDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
