# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qovery-ws.api.deployment_api import DeploymentApi


class TestDeploymentApi(unittest.TestCase):
    """DeploymentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeploymentApi()

    def tearDown(self) -> None:
        pass

    def test_handle_deployment_logs_request(self) -> None:
        """Test case for handle_deployment_logs_request

        """
        pass

    def test_handle_deployment_status_request(self) -> None:
        """Test case for handle_deployment_status_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
