# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery-ws.models.container_status_dto import ContainerStatusDto

class TestContainerStatusDto(unittest.TestCase):
    """ContainerStatusDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContainerStatusDto:
        """Test ContainerStatusDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContainerStatusDto`
        """
        model = ContainerStatusDto()
        if include_optional:
            return ContainerStatusDto(
                current_state = qovery-ws.models.container_state_dto.ContainerStateDto(
                    started_at = null, 
                    state = 'STARTING', 
                    state_message = '', 
                    state_reason = '', ),
                image = '',
                last_terminated_state = qovery-ws.models.container_state_terminated_dto.ContainerStateTerminatedDto(
                    exit_code = 56, 
                    exit_code_message = '', 
                    finished_at = null, 
                    message = '', 
                    reason = '', 
                    signal = 56, 
                    started_at = null, ),
                name = '',
                restart_count = 0
            )
        else:
            return ContainerStatusDto(
                image = '',
                name = '',
                restart_count = 0,
        )
        """

    def testContainerStatusDto(self):
        """Test ContainerStatusDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
