"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.container_status_dto_current_state import ContainerStatusDtoCurrentState
from qovery-ws.model.container_status_dto_last_terminated_state import ContainerStatusDtoLastTerminatedState
globals()['ContainerStatusDtoCurrentState'] = ContainerStatusDtoCurrentState
globals()['ContainerStatusDtoLastTerminatedState'] = ContainerStatusDtoLastTerminatedState
from qovery-ws.model.container_status_dto import ContainerStatusDto


class TestContainerStatusDto(unittest.TestCase):
    """ContainerStatusDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerStatusDto(self):
        """Test ContainerStatusDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContainerStatusDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
