"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery-ws
from qovery-ws.model.node_condition_dto import NodeConditionDto


class TestNodeConditionDto(unittest.TestCase):
    """NodeConditionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeConditionDto(self):
        """Test NodeConditionDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodeConditionDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
