# flake8: noqa

"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


__version__ = "0.1.0"

# import ApiClient
from qovery.api_client import ApiClient

# import Configuration
from qovery.configuration import Configuration

# import exceptions
from qovery.exceptions import OpenApiException
from qovery.exceptions import ApiAttributeError
from qovery.exceptions import ApiTypeError
from qovery.exceptions import ApiValueError
from qovery.exceptions import ApiKeyError
from qovery.exceptions import ApiException
