# flake8: noqa

"""
    websocket-gateway

    Describe the weboscket endpoints  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by: https://openapi-generator.tech
"""


__version__ = "0.1.0"

# import ApiClient
from qovery-ws.api_client import ApiClient

# import Configuration
from qovery-ws.configuration import Configuration

# import exceptions
from qovery-ws.exceptions import OpenApiException
from qovery-ws.exceptions import ApiAttributeError
from qovery-ws.exceptions import ApiTypeError
from qovery-ws.exceptions import ApiValueError
from qovery-ws.exceptions import ApiKeyError
from qovery-ws.exceptions import ApiException
