# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List
from pydantic import BaseModel, Field, StrictStr, conlist
from qovery-ws.models.pod_status_dto import PodStatusDto
from qovery-ws.models.service_state_dto import ServiceStateDto

class DatabaseStatusDto(BaseModel):
    """
    DatabaseStatusDto
    """
    id: StrictStr = Field(...)
    pods: conlist(PodStatusDto) = Field(...)
    state: ServiceStateDto = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["id", "pods", "state"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DatabaseStatusDto:
        """Create an instance of DatabaseStatusDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in pods (list)
        _items = []
        if self.pods:
            for _item in self.pods:
                if _item:
                    _items.append(_item.to_dict())
            _dict['pods'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DatabaseStatusDto:
        """Create an instance of DatabaseStatusDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DatabaseStatusDto.parse_obj(obj)

        _obj = DatabaseStatusDto.parse_obj({
            "id": obj.get("id"),
            "pods": [PodStatusDto.from_dict(_item) for _item in obj.get("pods")] if obj.get("pods") is not None else None,
            "state": obj.get("state")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


