# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NodeConditionDto(BaseModel):
    """
    NodeConditionDto
    """ # noqa: E501
    last_heartbeat_time: Optional[StrictInt] = Field(default=None, description="Unix timestamp with millisecond precision")
    last_transition_time: Optional[StrictInt] = Field(default=None, description="Unix timestamp with millisecond precision")
    message: StrictStr
    reason: StrictStr
    status: StrictStr
    type: StrictStr
    __properties: ClassVar[List[str]] = ["last_heartbeat_time", "last_transition_time", "message", "reason", "status", "type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NodeConditionDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if last_heartbeat_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_heartbeat_time is None and "last_heartbeat_time" in self.model_fields_set:
            _dict['last_heartbeat_time'] = None

        # set to None if last_transition_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_transition_time is None and "last_transition_time" in self.model_fields_set:
            _dict['last_transition_time'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NodeConditionDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "last_heartbeat_time": obj.get("last_heartbeat_time"),
            "last_transition_time": obj.get("last_transition_time"),
            "message": obj.get("message"),
            "reason": obj.get("reason"),
            "status": obj.get("status"),
            "type": obj.get("type")
        })
        return _obj


