# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class NodeConditionDto(BaseModel):
    """
    NodeConditionDto
    """
    last_heartbeat_time: Optional[StrictInt] = Field(None, description="Unix timestamp with millisecond precision")
    last_transition_time: Optional[StrictInt] = Field(None, description="Unix timestamp with millisecond precision")
    message: StrictStr = Field(...)
    reason: StrictStr = Field(...)
    status: StrictStr = Field(...)
    type: StrictStr = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["last_heartbeat_time", "last_transition_time", "message", "reason", "status", "type"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NodeConditionDto:
        """Create an instance of NodeConditionDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if last_heartbeat_time (nullable) is None
        # and __fields_set__ contains the field
        if self.last_heartbeat_time is None and "last_heartbeat_time" in self.__fields_set__:
            _dict['last_heartbeat_time'] = None

        # set to None if last_transition_time (nullable) is None
        # and __fields_set__ contains the field
        if self.last_transition_time is None and "last_transition_time" in self.__fields_set__:
            _dict['last_transition_time'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NodeConditionDto:
        """Create an instance of NodeConditionDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NodeConditionDto.parse_obj(obj)

        _obj = NodeConditionDto.parse_obj({
            "last_heartbeat_time": obj.get("last_heartbeat_time"),
            "last_transition_time": obj.get("last_transition_time"),
            "message": obj.get("message"),
            "reason": obj.get("reason"),
            "status": obj.get("status"),
            "type": obj.get("type")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


