# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conint, conlist
from qovery-ws.models.container_status_dto import ContainerStatusDto
from qovery-ws.models.service_state_dto import ServiceStateDto

class PodStatusDto(BaseModel):
    """
    PodStatusDto
    """
    containers: conlist(ContainerStatusDto) = Field(...)
    name: StrictStr = Field(...)
    restart_count: conint(strict=True, ge=0) = Field(...)
    service_version: StrictStr = Field(...)
    started_at: Optional[StrictInt] = Field(None, description="Unix timestamp with millisecond precision")
    state: ServiceStateDto = Field(...)
    state_message: StrictStr = Field(...)
    state_reason: StrictStr = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["containers", "name", "restart_count", "service_version", "started_at", "state", "state_message", "state_reason"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PodStatusDto:
        """Create an instance of PodStatusDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in containers (list)
        _items = []
        if self.containers:
            for _item in self.containers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['containers'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if started_at (nullable) is None
        # and __fields_set__ contains the field
        if self.started_at is None and "started_at" in self.__fields_set__:
            _dict['started_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PodStatusDto:
        """Create an instance of PodStatusDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PodStatusDto.parse_obj(obj)

        _obj = PodStatusDto.parse_obj({
            "containers": [ContainerStatusDto.from_dict(_item) for _item in obj.get("containers")] if obj.get("containers") is not None else None,
            "name": obj.get("name"),
            "restart_count": obj.get("restart_count"),
            "service_version": obj.get("service_version"),
            "started_at": obj.get("started_at"),
            "state": obj.get("state"),
            "state_message": obj.get("state_message"),
            "state_reason": obj.get("state_reason")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


