# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ResourceStatusDto(str, Enum):
    """
    ResourceStatusDto
    """

    """
    allowed enum values
    """
    OK = 'OK'
    WARNING = 'WARNING'
    ALERT = 'ALERT'

    @classmethod
    def from_json(cls, json_str: str) -> ResourceStatusDto:
        """Create an instance of ResourceStatusDto from a JSON string"""
        return ResourceStatusDto(json.loads(json_str))


