# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ServiceType(str, Enum):
    """
    ServiceType
    """

    """
    allowed enum values
    """
    APPLICATION = 'APPLICATION'
    CONTAINER = 'CONTAINER'
    DATABASE = 'DATABASE'
    JOB = 'JOB'
    HELM = 'HELM'

    @classmethod
    def from_json(cls, json_str: str) -> ServiceType:
        """Create an instance of ServiceType from a JSON string"""
        return ServiceType(json.loads(json_str))


