# coding: utf-8

"""
    websocket-gateway

    Describe the weboscket endpoints

    The version of the OpenAPI document: 0.1.0
    Contact: erebe@erebe.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class UnitDto(str, Enum):
    """
    UnitDto
    """

    """
    allowed enum values
    """
    MCPU = 'mCPU'
    MIB = 'MiB'
    GIB = 'GiB'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UnitDto from a JSON string"""
        return cls(json.loads(json_str))


